version: "3.9"

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - prod_db
    env_file:
      - ./.env.prod

  prod_db:
    image: postgres:15
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_PORT=${POSTGRES_PORT}

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles/
      - ./media:/app/media/
    depends_on:
      - web
volumes:
  postgres_prod: