version: "3.9"

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - prod_db
    environment:
      - "DJANGO_SECRET_KEY=PROD-SECRET-KEY"
      - "DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@prod_db:${POSTGRES_PORT}/${POSTGRES_DB}"
      - "DJANGO_DEBUG=False"

  prod_db:
    image: postgres:15
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - nginx

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles/
      - ./media:/app/media/
volumes:
  postgres_prod: