version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - dev_db
    environment:
      - "DJANGO_SECRET_KEY=DEBUG-SECRET-KEY"
      - "DATABASE_URL=postgres://postgres@dev_db/postgres"
      - "DJANGO_DEBUG=True"

  dev_db:
    image: postgres:15
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    depends_on:
      - nginx

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./static:/app/static/
      - ./media:/app/media/
volumes:
  postgres_dev: