version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - dev_db
    env_file:
      - ./.env.dev

  dev_db:
    image: postgres:15
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_PORT=${POSTGRES_PORT}

  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - web
volumes:
  postgres_dev: